### ISSUE TITLE
license is impossible

### ISSUE THREAD

**Issue by ceejayoz** [nix23/gridifier#3]
> You can use Gridifier for free under the non-commercial license. Non-commercial license is valid only if you are creating non-profit and personal projects. In such cases Gridifier license is GPLv3.

GPLv3 guarantees users the rights to share the software with anyone they choose, including in a commercial capacity. It cannot be both "non-commercial" and GPLv3. From the license:

> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.
> 
> You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.

Additionally:

> If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, **you may remove that term**.

Consider revising your site to dual license with something like a Creative Commons [BY-NC-SA / Attribution-NonCommercial-ShareAlike](https://creativecommons.org/licenses/by-nc-sa/4.0) license instead of the GPL. Unfortunately, the cat's already a bit out of the bag - anyone who's downloaded thus far has a valid GPL license to the codebase already.

**Comment by nix23** [comment]
Yeah, you are right about that points about GPLv3. However as license claims:
"Any use of Gridifier for a commercial purpose is subject to and requires a commercial license. With commercial license GPLv3 license terms are not used. Instead of that, terms described on developer license page are applyied."
That means, if product is being used for commercial purposes, GPLv3 license rules can not be applied at all.

**Comment by ceejayoz** [comment]
> That means, if product is being used for commercial purposes, GPLv3 license rules can not be applied at all.

No, that's not how it works. If I want to use the project commercially, without paying the commercial license, here's what I do.
1. Download the non-commercial version.
2. Distribute it to myself, under the GPL. As the GPL section 7 states, I'm allowed to remove your non-commercial restriction as it's not valid under the GPL.
3. Use commercially!

If you want to prevent people from using your free version commercially, **you must pick another license**.

**Comment by nix23** [comment]
Ok, I have read section 7 one more time and debates over the internet. Yeah, as I see many users are unhappy with such type of dual licensing and it seems it is just useless in trying to combine Open Source/Commercial license. Because of that we have switched to https://creativecommons.org/licenses/by-nc-sa/4.0/. Thanks for explanation.

**Comment by nix23** [comment]
Switched to https://creativecommons.org/licenses/by-nc-sa/4.0/. (For non-commercial license)

**Comment by ceejayoz** [comment]
@nix23 That should suit your desire to generate commercial revenue much better. Thanks for listening. :+1:
