### ISSUE TITLE
onDisconnect callback not being called if events happen simultaneously

### ISSUE THREAD

**Issue by MayamaTakeshi** [nix23/gridifier#6]
Sample:
  https://jsfiddle.net/7xyz7xxg/
In the above, I am adding and removing 10 items, each 2 of them at the same time.
But onDisconnect callback is called for only one of them in the pair.
If I just change ITEMS_PER_ITERATION from 2 to 1 like here:
  https://jsfiddle.net/7xyz7xxg/1/
then I get proper notification of 'disconnect'.
Looks like a bug to me.

**Comment by MayamaTakeshi** [comment]
Sorry. I am trying to reproduce a problem I am seeing in my app and got it wrong in the jsfiddle test.
Just for reference, here is a corrected version that shows the reported issue doesn't happen even with 100 items:
https://jsfiddle.net/7xyz7xxg/2/

**Comment by nix23** [comment]
Ok, nice. I saw that you have called reposition() function in your fiddle code:
1) Usually there is no need to call reposition() directly. All gridifier operations(like disconnect,append,etc..) are calling this function internally.
2) So, reposition function will be useful after some custom manipulations with grid items. (Without calls of gridifier functions). For example, if you will add resize buttons to each of your items, you will call reposition fn at points when you want trigger all grid items reposition.

I am not sure, but if you have called it because of items 1-12 being placed each on new row at script run:
children div of item will have 100% width(auto rule will be applied) until moment when position: 'absolute' rule will be set on that item by gridifier.(So, after any resize or reposition() call (after item was appended) items will be placed in correct order.) To correctly place items on init preinit items with position: 'absolute' rule:

``` html
<div class="item" style="visibility: hidden; position: absolute; left: 0px; top: 0px;">....</div>
```

**Comment by MayamaTakeshi** [comment]
Ah, yes. After doing some tinkering I got into the habit of calling reposition() to force items to be placed horizontally when possible (although as you noticed, it didn't quite work on my last jsfiddle attempt above).
I tried disabling calls to reposition() and used position: 'absolute' as you suggested but it didn't work:
https://jsfiddle.net/7xyz7xxg/3/

**Comment by nix23** [comment]
Looks like it is a bug if item is added to DOM through append() fn call. You can use this tmp solution:

``` javascript
...
$("#grid").append(item); // Add item to DOM manually using jQuery
grid.append(item); // Call append to reposition item
// Append internally is called after little delay with setTimeout, so it looks item
 // styles are propogated right in this case.(getComputedStyle for item is correct)
```

Looks like when getComputedStyle is called right after appendChild call(inside grid.append(item) fn), item position: 'absolute' style isn't calculated correctly yet. I will inspect bug now and look how to flush item computed style right after adding to DOM tree.

**Comment by MayamaTakeshi** [comment]
Thanks. It worked.
