### ISSUE TITLE
OnDisconnect callback not being called for filtered out items

### ISSUE THREAD

**Issue by MayamaTakeshi** [nix23/gridifier#7]
Scenario is this:
- items 1, 2 and 3 are created and added to the grid
- items 2 is filtered out
- items 1 and 2 are disconnected
- onDisconnect is called for item 1 but not for item 2
- filter is disabled and item 2 shows up

Evidence:
 https://jsfiddle.net/m40q88jd/1/

**Comment by nix23** [comment]
Currently only connected(not filtered out) items can be used inside disconnect/pop/shift function calls. Item 2 is filtered out, so it will be dropped out inside disconnect call on line 34. It seems logical, because currently I can see only 1 use case for onDisconnect event:
1) Do something useful after hide animation finish, usually delete item from DOM and optionally increase/decrease some grid counters;

When item 2 was filtered out, it's hide animation was already executed. So it makes no sense to execute it again. Of course we could just send onDisconnect event for filtered out items and return from function, but it can produce some bugs: on grids with collection synchronization disconnect function can be called multiple times with same item and if you are doing something with item inside onDisconnect callback you will start getting errors with successive calls.(If item was deleted inside first callback)

So, if you have use-case when grid items are representing some synced collection of models with backend and you are receiving 'delete' event while item is filtered out, a more stable approach for deleting item from DOM will be like this:
1) Get all connected items -> var connectedItems = grid.all(); (All iterators are returning only visible items)
2) Get item to delete -> var itemToRm = // Get item to remove by received model id
3) Iterate through all connectedItems and compare model ids
4) If deleted item is connected -> call disconnect function - grid.disconnect(itemToRm);
5) else just delete item from DOM -> item.parentNode.removeChild(item);

**Comment by MayamaTakeshi** [comment]
OK. Understood.
I have updated the code as you suggested and now it is OK:
https://jsfiddle.net/m40q88jd/3/

Thanks.
